import 'package:chodan_flutter_app/core/service/chat_user_service.dart';
import 'package:chodan_flutter_app/features/auth/controller/auth_controller.dart';
import 'package:chodan_flutter_app/features/auth/service/token_service.dart';
import 'package:chodan_flutter_app/features/banner/controller/banner_controller.dart';
import 'package:chodan_flutter_app/features/company/controller/company_controller.dart';
import 'package:chodan_flutter_app/features/jobposting/controller/jobposting_controller.dart';
import 'package:chodan_flutter_app/features/mypage/controller/mypage_controller.dart';
import 'package:chodan_flutter_app/features/user/controller/user_controller.dart';
import 'package:chodan_flutter_app/features/worker/controller/worker_controller.dart';
import 'package:chodan_flutter_app/router.dart';
import 'package:chodan_flutter_app/router_notifier.dart';
import 'package:flutter/material.dart';
import 'package:flutter_naver_login/flutter_naver_login.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';

Future<void> logout(WidgetRef ref, BuildContext context) async {
  final prefs = await SharedPreferences.getInstance();
  await chatUserService.deleteUserDeviceToken();
  TokenService tokenService = TokenService();
  await tokenService.logout();
  await FlutterNaverLogin.logOut();
  prefs.remove('token');
  ref.invalidate(userProvider);
  ref.invalidate(userAuthProvider);
  ref.invalidate(chatUserAuthProvider);
  ref.invalidate(chatUserMsgCountAuthProvider);
  ref.invalidate(chatUserRoomProvider);
  ref.invalidate(chatUserRoomInfoProvider);
  ref.invalidate(chatPartnerRoomInfoProvider);
  ref.invalidate(chatPartnerMsgCountProvider);
  ref.invalidate(userClipAnnouncementListProvider);
  ref.invalidate(userProfileListProvider);
  ref.invalidate(companyLikesKeyListProvider);
  ref.invalidate(companyHidesKeyListProvider);
  ref.invalidate(lastJobpostProvider);
  ref.invalidate(applyOrProposedJobpostKeyListProvider);
  ref.invalidate(workerLikesKeyListProvider);
  ref.invalidate(workerHidesKeyListProvider);
  ref.invalidate(matchingKeyListProvider);
  ref.invalidate(userListProvider);
  ref.invalidate(userAllListProvider);
  ref.invalidate(otherUserProvider);
  ref.invalidate(userAuthProvider);
  ref.invalidate(userEmailProvider);
  ref.invalidate(inviteProvider);
  ref.invalidate(userSingFinishProvider);
  ref.invalidate(userProfileProvider);
  ref.invalidate(popupBannerListProvider);
  ref.invalidate(popupBeltBannerListProvider);
  ref.invalidate(menuBannerListProvider);
  ref.invalidate(jobPostingBannerListProvider);
  ref.invalidate(jobSeekerBannerListProvider);
  ref.invalidate(themeBannerListProvider);
  ref.invalidate(chatUserRoomStatusProvider);

  ref.read(goRouterNotifierProvider).isLoggedIn = false;
  chatUserService.setUserStatus(false);
  disposeChatService();
  disposeChatRoomService();
  ref.watch(goRouterProvider).go('/');
}
